# Generated by Django 2.0.7 on 2020-08-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_description', models.TextField(max_length=1000)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product_image_url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=20)),
                ('receipt_url', models.URLField(max_length=500)),
                ('mobile_no', models.IntegerField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_id', models.CharField(blank=True, max_length=50)),
                ('transaction_status', models.CharField(choices=[('S', 'Success'), ('F', 'Failure')], max_length=1)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ManyToManyField(null=True, to='stripe_payment.ProductModel')),
            ],
        ),
    ]
